### ISSUE TITLE
Add `Category` as a Kubernetes object search criteria

### ISSUE THREAD

**Issue by vladimirvivien** [vmware-tanzu/crash-diagnostics#116]
The search function in package `k8s` currently takes into account resource name, kind, namespaced, group, and version.  This issue is to add support to query objects using the `Category` field of the resource.

See 
https://github.com/kubernetes/apimachinery/blob/2a468d8caa4629500c086c621f2cb3402168c6a3/pkg/apis/meta/v1/types.go#L1022

**Comment by ncdc** [comment]
@vladimirvivien this would be very helpful for pulling down Cluster API resources. Do you know when this might be worked on? Thanks!

**Comment by vladimirvivien** [comment]
@ncdc We are making support for CAPI top priority in upcoming releases, so this will be one of them.  Not sure exactly when but next release for sure.

**Comment by vladimirvivien** [comment]
@ncdc there is a PR for this inflight and should merge soon - https://github.com/vmware-tanzu/crash-diagnostics/pull/184

**Comment by ykakarap** [comment]
Closing issue. 
MR [#184](https://github.com/vmware-tanzu/crash-diagnostics/pull/184) implements `categories` search.
