### ISSUE TITLE
Update `kube_config` to add context as a supported parameter

### ISSUE THREAD

**Issue by srm09** [vmware-tanzu/crash-diagnostics#122]
Add a `context` parameter to override the `current-context` from the kubeconfig which is the default context.

**Comment by reasonerjt** [comment]
hello, 
@srm09 
I'm trying to levelrate `crashd` to collect logs for `velero` and this feature is helpful for making the parms more consistent for velero users.

May I know if this is still to be worked on?

**Comment by vladimirvivien** [comment]
@reasonerjt 
I will move this up in importance and priority so we can work on it.

Thanks.
