### ISSUE TITLE
Provide a way to detect if a program on the command path

### ISSUE THREAD

**Issue by vladimirvivien** [vmware-tanzu/crash-diagnostics#181]
As a script writer I should be able to check whether a program is on the command path of a local or remote machine.  This will allow to do some verification step prior to executing the script.

#### Example
```
[]cmdResult=prog_avail(prog=<program-name>, [resources=<resource-list>])

# or

path=prog_avail_local(prog=<prog-name>)
```
 Where []cmdResult is a list of command result from each compute resource.

**Comment by johnSchnake** [comment]
Fixed by https://github.com/vmware-tanzu/crash-diagnostics/pull/187
