### ISSUE TITLE
Make KubeConfigFn honor the KUBECONFIG env var

### ISSUE THREAD

**Issue by reasonerjt** [vmware-tanzu/crash-diagnostics#208]
The `KubeConfigFn` loads the kubeconfig  file based on the input parms `path` or `capi_provider`:
https://github.com/vmware-tanzu/crash-diagnostics/blob/main/starlark/kube_config.go#L31

I'd like to know the maintainers' thought on whether it should honor the conventional path `$HOME/.kube` and environment variable `KUBECONFIG`

Seems we can leverage the `PathOptions` in client-go:
https://github.com/kubernetes/client-go/blob/228dada99554f2e0f7ef07e24f2a4a88c0e448bb/tools/clientcmd/config.go#L47

**Comment by vladimirvivien** [comment]
@reasonerjt 
The `kube_config` forces script author to specify where the kubeconfig is coming from.  

I would stay away from having kube_config automatically set the path. Instead,  this can be done as:

```pythonk
kube_capture(what="logs", namespaces=["default"], kube_config=kube_config(path=os.getenv("KUBECONFIG")))
```

**Comment by reasonerjt** [comment]
@vladimirvivien 
Some background
I'm using `crashd` as library to collect logs for velero.  
Anyway I think I can use similar approach to locate the file path in velero's code, thanks for the clarification.
