### ISSUE TITLE
If no workload cluster is specified in capv_provider names and label searches are swapped

### ISSUE THREAD

**Issue by perithompson** [vmware-tanzu/crash-diagnostics#226]
A while ago I submitted PR https://github.com/vmware-tanzu/crash-diagnostics/pull/205 to correct an error when a label filter and names filter were reversed.  It seems that if I do not specify a workload cluster in capv_provider, names and labels reverse meaning. 

```
wc_provider_cp=capv_provider(
    ssh_config=ssh_conf,
    mgmt_kube_config=kube_conf,
    nodes=['node-role.kubernetes.io/control-plane=']
)
```
results in
```
U[0001] Searching for resource nodes/status (non-namespaced) 
DEBU[0001] WARN: K8s.Search failed to get nodes/status: [GroupRes: v1] [labels: ]: nodes "status" not found 
DEBU[0001] Search filters groups:[core]; categories:[]; kinds:[nodes]; namespaces:[]; versions:[]; names:[]; labels:[node-role.kubernetes.io/control-plane] containers:[] 
```

**Comment by perithompson** [comment]
@vladimirvivien @sfzylad any ideas why this might be? I need to double check this on Monday but I'm very confused!

**Comment by perithompson** [comment]
never mind, i messed up my binary! its fine closing this

**Comment by vladimirvivien** [comment]
👍
