### ISSUE TITLE
Failed to parse quotes of command in two cases

### ISSUE THREAD

**Issue by YanzhaoLi** [vmware-tanzu/crash-diagnostics#23]
1. `RUN bash -c "ulimit -a"`, in this case,  the actually command becomes `bash -c ulimit`. That's because the  `func cmdParse(` removed the `" "`

2. `RUN bash -c 'for xxx' `, in this case, there would be an error. The reason is the last line of  `func makeNamedPram(  `, which quotes string by `' '`

**Comment by vladimirvivien** [comment]
@YanzhaoLi 
Thanks for reporting this.  I have that documented in #17, it's a known issue. The work arounds for now:
- Quote the entire default RUN parameter as: `RUN "bash -c 'ulimit -a'"`
- Or use the named parameter format:`RUN cmd:"bash -c 'ulimit -a'"`

Let me know if that fixes your issue.

**Comment by YanzhaoLi** [comment]
@vladimirvivien Unfortunately it doesn't work because the `' '` were removed by function 
 `cmdParse()` -> `wordSplit()`.
Output: `DEBU[0009]Capturing remote command [/bin/bash -c "ulimit -a"]
DEBU[0009] Running remote command: /bin/bash -c ulimit -a`, and the output contents only contain `unlimited`

**Comment by vladimirvivien** [comment]
@YanzhaoLi I will investigate this to put out a patch this morning.  Thanks again.

**Comment by vladimirvivien** [comment]
@YanzhaoLi please take a look - https://github.com/vmware-tanzu/crash-diagnostics/releases/tag/v0.1.0-alpha.9
