### ISSUE TITLE
Issue in parsing the command string while using RUN or CAPTURE

### ISSUE THREAD

**Issue by pnarasimhapr** [vmware-tanzu/crash-diagnostics#26]
While passing a command to the RUN or CAPTURE command, I see that the parsing is incorrect.

`DEBU[0000] Parsing [67: RUN /bin/bash -c 'sudo find /home/cluster-info-dump -maxdepth 2 -type d -print0 |  while IFS= read -rd "" dir; do for file in $dir; do mkdir -p /home/vmware-system-wcp/cluster-info/$file; files=`sudo find $file -maxdepth 1 -type f`; for sf in $files; do sudo cat $sf>/home/vmware-system-wcp/cluster-info/$sf; done; done; done']`

However, the argument passed to the RUN command is has missing strings.
For example: $dir in `do for file in $dir`, similarly $file in `sudo find $file -maxdepth` .

The complete SSHRun debug statement  - 

`SSHRun: /bin/bash -c 'sudo find /home/cluster-info-dump -maxdepth 2 -type d -print0 |  while IFS= read -rd "" dir; do for file in ; do mkdir -p /home/vmware-system-wcp/cluster-info/; files=`sudo find  -maxdepth 1 -type f`; for sf in ; do sudo cat >/home/vmware-system-wcp/cluster-info/; done; done; done'`
The above command fails since it has missing strings.

I have verified manually that the command passed to RUN/CAPTURE in the Diagnostics file works when executed directly on the remote machine.

Looking at the code seems like `GetEffectiveCmd` calls `wordSplit`. I think this function might need to be modified to take care of this ?

My Diagnostics.file looks like this - 

FROM 10.78.106.74:22
AUTHCONFIG username:vmware-system-wcp private-key:/Users/pnarasimhapr/go/src/gitlab.eng.vmware.com/guest-clusters/dev-bootstrap/bin/new-cluster-ssh-key
WORKDIR /tmp/crashdir
RUN /bin/bash -c ' sudo rm -rf /home/cluster-info-dump; rm -rf /home/vmware-system-wcp/cluster-info/; sudo mkdir -p /home/cluster-info-dump;sudo kubectl --kubeconfig /etc/kubernetes/admin.conf cluster-info dump --output-directory=/home/cluster-info-dump'
RUN /bin/bash -c 'sudo find /home/cluster-info-dump -maxdepth 2 -type d -print0 |  while IFS= read -rd "" dir; do for file in $dir; do mkdir -p /home/vmware-system-wcp/cluster-info/$file; files=`sudo find $file -maxdepth 1 -type f`; for sf in $files; do sudo cat $sf>/home/vmware-system-wcp/cluster-info/$sf; done; done; done'
COPY /home/vmware-system-wcp/cluster-info/`

**Comment by vladimirvivien** [comment]
@pnarasimhapr thanks for reporting issue.  Your second RUN command seems to be quite a lot of logic. So, make sure in your original diagnostics file that your quotes are balanced.  I noticed that the command has nested quotes, make sure those are balanced as well.

**Comment by vladimirvivien** [comment]
@pnarasimhapr can you repost your diagnostics file pre-formatted encoded in \` \`\` ... \`\`\`.  It looks like there are some missing back ticks that got interpreted by the github editor.

**Comment by pnarasimhapr** [comment]
```
FROM 10.78.106.74:22
AUTHCONFIG username:vmware-system-wcp private-key:/Users/pnarasimhapr/go/src/gitlab.eng.vmware.com/guest-clusters/dev-bootstrap/bin/new-cluster-ssh-key
WORKDIR /tmp/crashdir
RUN /bin/bash -c ' sudo rm -rf /home/cluster-info-dump; rm -rf /home/vmware-system-wcp/cluster-info/; sudo mkdir -p /home/cluster-info-dump;sudo kubectl --kubeconfig /etc/kubernetes/admin.conf cluster-info dump --output-directory=/home/cluster-info-dump'
RUN /bin/bash -c 'sudo find /home/cluster-info-dump -maxdepth 2 -type d -print0 |  while IFS= read -rd "" dir; do for file in $dir; do mkdir -p /home/vmware-system-wcp/cluster-info/$file; files=`sudo find $file -maxdepth 1 -type f`; for sf in $files; do sudo cat $sf>/home/vmware-system-wcp/cluster-info/$sf; done; done; done'
COPY /home/vmware-system-wcp/cluster-info/
```

**Comment by pnarasimhapr** [comment]
I also tried a simple command from the issue you had mentioned to me in slack as a work around
 - https://github.com/vmware-tanzu/crash-diagnostics/issues/4#issuecomment-540926598
The diagnostic file  - 
```
FROM 10.199.56.206:22 10.199.56.195:22 10.199.56.200:22 10.199.56.201:22
ENV CLUSTER_USER_NAME=vmware-system-user
ENV CLUSTER_SSH_KEY=cluster1-key
AUTHCONFIG username:$CLUSTER_USER_NAME private-key:$CLUSTER_SSH_KEY

# WORKDIR specifies a location on disk
# where the tool collects information
WORKDIR /storage/log/cluster1-crash-dir

OUTPUT /storage/log/cluster1-support-bundle.tar.gz
RUN /bin/bash -c 'mkdir -p /tmp/containers; for file in $(ls /var/log/containers/); do sudo cat /var/log/containers/$file > /tmp/containers/$file; done'
COPY /tmp/containers
RUN /usr/bin/rm -rf /tmp/containers
```
Looks like this has the same parsing issue as I had mentioned earlier. The output from the run - 

```
DEBU[0000] Parsing [12: OUTPUT /storage/log/cluster1-support-bundle.tar.gz]
DEBU[0000] OUTPUT parsed OK
DEBU[0000] Parsing [16: RUN /bin/bash -c 'mkdir -p /tmp/containers; for file in $(ls /var/log/containers/); do sudo cat /var/log/containers/$file > /tmp/containers/$file; done']
DEBU[0000] RUN parsed OK
....
....
DEBU[0016] SSHRun: /bin/bash -c 'mkdir -p /tmp/containers; for file in $(ls /var/log/containers/); do sudo cat /var/log/containers/ > /tmp/containers/; done'
ERRO[0017] RUN remote command failed: /bin/bash -c 'mkdir -p /tmp/containers; for file in $(ls /var/log/containers/); do sudo cat /var/log/containers/ > /tmp/containers/; done': SSH: error waiting for response: Process exited with status 1
DEBU[0017] Entering remote COPY command: map[paths:/tmp/containers]
```
The above ```ssh``` command seems to miss ```$file```.

**Comment by vladimirvivien** [comment]
@pnarasimhapr t hank you for the follow up. I am labeling this a bug to move it in priority.

**Comment by vladimirvivien** [comment]
@pnarasimhapr I think I found the issue. Variable `$file` is getting interpreted early by the tool's variable expansion phase.  Since `file` was not declare using the diagnostics script, it is blanked out.  I am going to work on a fix or workaround.  Thanks for finding this.

**Comment by vladimirvivien** [comment]
@pnarasimhapr release v0.1.1 introduced code to fix this issue. You can now use `\$` to escape variable expansion so that Crash Diagnostics does not attempt to expand the variable but instead send it the server.
