### ISSUE TITLE
Option to run certain commands on particular kind of nodes and not on all nodes specified in the FROM directive

### ISSUE THREAD

**Issue by pnarasimhapr** [vmware-tanzu/crash-diagnostics#29]
I have deployed a cluster with 1 Master and 1 worker nodes.
The kubeconfig on the master and workers are different files.
Master -  /etc/kubernetes/admin.conf 
Workers - /etc/kubernetes/kubelet.conf

My Diagnostic.file looks like the following - 
```
FROM 10.161.116.163:22 10.161.109.198:22
ENV CLUSTER_USER_NAME=vmware-system-user
ENV CLUSTER_SSH_KEY=/Users/pnarasimhapr/go/src/gitlab.eng.vmware.com/guest-clusters/dev-bootstrap/bin/madhwa-100-ssh-key
AUTHCONFIG username:$CLUSTER_USER_NAME private-key:$CLUSTER_SSH_KEY
WORKDIR /tmp/crashdir
RUN /bin/bash -c ' sudo rm -rf /home/cluster-info-dump; rm -rf /home/vmware-system-user/cluster-info/; sudo mkdir -p /home/cluster-info-dump;sudo kubectl --kubeconfig /etc/kubernetes/admin.conf cluster-info dump --output-directory=/home/cluster-info-dump'
```

The RUN command tries to run the `kubectl cluster-info dump` on all nodes. Since `kubectl` take a `kubeconfig` as an option and we have 2 different sets of nodes(masters and workers) with different kubeconfig files, is there a way we can specify if we want to run a command only on a particular kind of nodes so that the specified `kubeconfig` is valid on that node ?

**Comment by vladimirvivien** [comment]
@pnarasimhapr that is a great idea.  I have been thinking about something similar as well.  

Note that in the next release, the task of running cluster-info dump will not be done automatically and must be declared using `KUBEGET`.

**Comment by pnarasimhapr** [comment]
Thanks @vladimirvivien . The cluster-dump that you have mentioned above is the one that's captured as a json file(cluster-dump.json).
This however does not capture log files in the `kube-system` and `default` namespaces.
Can all of these log files be captured ? The logic I added in https://github.com/vmware-tanzu/crash-diagnostics/issues/26 was aiming to capture these log files and more.

**Comment by vladimirvivien** [comment]
@pnarasimhapr As of release 0.2.0 the log capture has moved to KUBEGET tag so that an operator can capture specific log from any pod from any namespace.  Please take a look.
