### ISSUE TITLE
Needs command that do not capture content ?

### ISSUE THREAD

**Issue by YanzhaoLi** [vmware-tanzu/crash-diagnostics#4]
When we copy multiple files which needs `sudo` capability, scp doesn't work.  In this case, we could execute `sudo command` to copy these files to `/tmp` and then execute scp.  Thus, we need dummy command that does not capture content.

**Comment by vladimirvivien** [comment]
@YanzhaoLi thanks for the feedback.
Can you please paste an example Diagnostics.file here to show an example of what you are talking about.  Thanks!

**Comment by YanzhaoLi** [comment]
@vladimirvivien 
`
# To Copy multiple root-owned files
# Since we have no root user, we couldn't scp root-owned files such as container logs.
# Fortunately, we have sudo privilege, we make a trick to sudo copy these logs into where we can scp
CAPTURE /bin/bash -c 'mkdir -p /tmp/containers; for file in $(ls /var/log/containers/); do sudo cat /var/log/containers/$file > /tmp/containers/$file; done'
COPY /tmp/containers
CAPTURE /usr/bin/rm -rf /tmp/containers
`
In this case, the two `CAPTURE` command would generate two useless files. How about add a `RUN` command which only run command instead of generating files

**Comment by vladimirvivien** [comment]
@YanzhaoLi thanks for this issue. 
I am looking into improving how commands are executed.
This is a great case to help with that. Looking into a solution Soon.

**Comment by vladimirvivien** [comment]
@YanzhaoLi Your requested feature is in!
