### ISSUE TITLE
[code reorg] Code to support compute resource enumerators

### ISSUE THREAD

**Issue by vladimirvivien** [vmware-tanzu/crash-diagnostics#67]
A resource enumerator knows how to allow discovery of compute resources capable of executing commands (see [design doc](https://docs.google.com/document/d/1pqYOdTf6ZIT_GSis-AVzlOTm3kyyg-32-seIfULaYEs/edit#heading=h.24xlmcp7u50l) for detail).

In order to support enumerator components, the code should be updated to allow directives to specify enumerators.

**Comment by srm09** [comment]
Updating the link in the description to point to the **Compute Resource Enumerator** heading
