### ISSUE TITLE
Ability to pass script-specific arguments

### ISSUE THREAD

**Issue by vladimirvivien** [vmware-tanzu/crash-diagnostics#98]
As a script developer, I should be able to pass in arguments specific to the script at runtime.  The arguments can be passed using the `--args` flag which would capture a key/value pair string as shown below:

```
crashd run --file filepath --args "arg0=val0 arg1=val1 ... argN=valN"
```
The arguments should be exposed to the script using the `args` struct as shown below:

```python
crashd_config(workdir=args.arg0, output=args.arg2)
```

**Comment by srm09** [comment]
fixed by #104
